### ISSUE TITLE
Error: Cannot find module './config.js'

### ISSUE THREAD

**Issue by fakela** [underlay/r1#4]
Following the steps on how to install and run dev mode. I got this error

<img width="815" alt="Screenshot 2020-10-17 at 2 35 18 PM" src="https://user-images.githubusercontent.com/39309699/96350987-90873280-10b0-11eb-8ce9-3e6bef852fb9.png">

I checked and found no config.js file under the server folder.

<img width="548" alt="Screenshot 2020-10-17 at 7 47 30 PM" src="https://user-images.githubusercontent.com/39309699/96351184-a6e1be00-10b1-11eb-9383-3e9cff4cabf1.png">

Commenting out line 5 removes the error 
<img width="487" alt="Screenshot 2020-10-17 at 2 36 05 PM" src="https://user-images.githubusercontent.com/39309699/96351403-efe64200-10b2-11eb-8e25-4271aa4bf033.png">

But this still doesn't work `localhost:9876`
`
Please, I need help with this.

**Comment by metasj** [comment]
Hi @fakela, it's changing quickly at the moment; we'll update when it's at a point that you might want to explore.
